services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro 

  glances:
    container_name: glances
    image: nicolargo/glances:latest
    command: glances -w  # Run Glances in web mode
    ports:
      - "61208:61208"  # Web UI
      - "61209:61209"  # API
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    privileged: true

  # cadvisor:
  #   container_name: cadvisor
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   ports:
  #     - "8081:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   restart: always
  #   privileged: true

  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    volumes:
      - ./kuma_data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
    restart: unless-stopped

  ddns-updater:
    container_name: ddns-updater
    image: qmcgaw/ddns-updater:latest
    network_mode: bridge
    ports:
      - 8000:8000/tcp
    volumes:
      - ./ddns-data:/updater/data
    restart: always

  nginx:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
      - "81:81"   # NPM Web UI
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt

  octoeverywhere-elegoo-connect:
    container_name: octoeverywhere-cc
    image: octoeverywhere/octoeverywhere:latest
    environment:
      - COMPANION_MODE=elegoo
      - PRINTER_IP=192.168.1.131
    restart: always
    volumes:
      - ./octo_data:/data

networks:
  web:
    driver: bridge
  internal:
    driver: bridge
