---
# Main tasks file for the Mattermost role

- name: Include NFS uploads mount tasks
  ansible.builtin.include_tasks: nfs.yml
  tags:
    - mattermost
    - nfs

- name: Include directory setup tasks
  ansible.builtin.include_tasks: directories.yml
  tags:
    - mattermost
    - directories

- name: Include Mattermost deployment tasks
  ansible.builtin.include_tasks: deploy.yml
  tags:
    - mattermost
    - deploy

- name: Include Mattermost bootstrap tasks
  ansible.builtin.include_tasks: bootstrap.yml
  tags:
    - mattermost
    - bootstrap
