---
# Create required directories for OTBR

- name: Create OTBR compose directory
  ansible.builtin.file:
    path: "{{ otbr_compose_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create OTBR base directory on NFS
  ansible.builtin.file:
    path: "{{ otbr_base_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create OTBR data directory
  ansible.builtin.file:
    path: "{{ otbr_data_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
