---
ha_mcp_version: "7.2.0"
ha_mcp_image: "ghcr.io/homeassistant-ai/ha-mcp:{{ ha_mcp_version }}"
ha_mcp_base_dir: "/srv/docker/ha-mcp"
ha_mcp_container_name: "ha-mcp"
ha_mcp_port: 8087
ha_mcp_homeassistant_url: "http://{{ hostvars['haos']['ansible_host'] }}:8123"
ha_mcp_token: "{{ vault_ha_mcp_token }}"
ha_mcp_service_state: "started"
