---
# Deploy and manage Immich with Docker Compose

- name: Pull Immich Docker images
  community.docker.docker_compose_v2:
    project_src: "{{ immich_base_dir }}"
    pull: "always"
  register: immich_pull
  notify: restart immich
