---
# Deploy and manage Immich with Docker Compose

- name: Deploy Immich Docker Compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ immich_base_dir }}"
    pull: "missing"  # Don't pull locally-built images (immich-ml-rocm-custom)
  register: immich_pull
  notify: restart immich
