---
# Playbook to configure the Docker Host VM (containers)
# This applies the common role and Docker role

- name: Configure Docker Host VM
  hosts: containers
  become: true
  vars_files:
    - secrets.yml
  roles:
    - common
    - docker
