---
# Create Docker network for monitoring stack

- name: Create monitoring Docker network
  community.docker.docker_network:
    name: "{{ monitoring_stack_docker_network }}"
    state: present
  tags:
    - monitoring-stack
    - docker
    - network
